name: Kubernetes Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for private repositories
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          version: latest

      - name: Deploy App (Deployment)
        run: |
          kubectl apply -f deploy.yaml --server=https://localhost:8443 
